name: clustering_google_maps
description: A Flutter package that recreates clustering technique in a Google Maps widget.
version: 0.1.2
homepage: https://github.com/giandifra/clustering_google_maps

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.3.0
  path_provider: ^2.0.14
  google_maps_flutter: ^2.5.0
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/m1.png
    - assets/images/m2.png
    - assets/images/m3.png
    - assets/images/m4.png
    - assets/images/m5.png
    - assets/images/m6.png
    - assets/images/m7.png
